default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host:     localhost
  username: railsgirls
  password: railsgirls

development:
  <<: *default
  database: railsgirls_dev

test:
  <<: *default
  database: railsgirls_test

production:
  <<: *default
  database: production
